# Generated by Django 3.0.3 on 2020-02-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20200214_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-publish'], 'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=256, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='publish',
            field=models.DateTimeField(verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=512, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=256, verbose_name='用户名'),
        ),
    ]
