# Generated by Django 3.0.3 on 2020-02-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmstring',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='确认码'),
        ),
        migrations.AlterField(
            model_name='confirmstring',
            name='code',
            field=models.CharField(max_length=256, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='confirmstring',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oauth.User', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='c_time',
            field=models.DateField(auto_now_add=True, verbose_name='确认码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False, verbose_name='确认情况'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别'),
        ),
    ]
